services:
  bass:
    build:
      context: .
      dockerfile: prod.dockerfile
    container_name: bass
    restart: always
    env_file:
      - .env
    ports:
      - "80:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 60s
