services:
  app:
    build:
      context: .
      dockerfile: dev.dockerfile
    container_name: bass
    restart: always
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - ./src:/home/gradle/project/src
      - ./build.gradle.kts:/home/gradle/project/build.gradle.kts
      - ./settings.gradle.kts:/home/gradle/project/settings.gradle.kts
      - ./gradle:/home/gradle/project/gradle
      - ~/.gradle:/home/gradle/.gradle
    networks:
      - bass-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 15s

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: bass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - bass-network
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${DB_USERNAME}"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  pgdata:

networks:
  bass-network:
    driver: bridge
